name: liquid_engine
description: A dart port of the liquid / django HTML template engine.
version: 0.2.5
homepage: https://github.com/ergonlabs/liquid_dart

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  string_scanner: ^1.3.0
  gato: ^0.0.5+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
